package KieRule;
import com.rule.drools.Order;

rule "HDFC"
when
orderObject : Order(cardType=="HDFC" && price>10000);
number: Integer(this > 100)
then
orderObject.setDiscount(10);
end;

rule "ICICI"

when
orderObject : Order(cardType=="ICICI" && price>15000);
number: Integer(this > 100)
then
orderObject.setDiscount(8);
end;

rule "DBS"

when
orderObject : Order(cardType=="DBS" && price>15000);
number: Integer(this > 100)
then
orderObject.setDiscount(15);
end;

rule "DBS1"

when
orderObject : Order(cardType=="DBS" && price>15000);
number: Integer(this > 200)
then
orderObject.setDiscount(20);
end;